apiVersion: v1
kind: Service
metadata:
  name: micro-service
  labels:
    app: micro-service
spec:
  type: NodePort
  ports:
  - port: 9100
    protocol: TCP
    targetPort: 9100
    nodePort: 30007
  selector:
    app: micro-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-service
  namespace: default
  labels:
    app: micro-service
spec:
  replicas: 15
  selector:
    matchLabels:
      app: micro-service
  template:
    metadata:
      labels:
        app: micro-service
    spec:
      containers:
      - name: micro-service
        image: lgracia/dev:micro-service 
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 756Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: NODE_ENV
          value: development
        ports:
        - containerPort: 9100